---
title: "Risk management"
author: "Santa_Jstiwer"
date: "2023-02-14"
output: html_document
---
#setup the markdown
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Run the libraries
```{r}
library(tidyverse)
library(quantmod)
library(highcharter)
library(forecast)
library(PerformanceAnalytics)
library(plotly)
library(tseries)
```
#Get the data
```{r}
getSymbols("EC", from = "2018-01-01", to = "2023-01-01")
head(EC)
```
#chart the data last six months
```{r}
chartSeries(EC, subset = "last 6 months", 
            type = "auto",
            )
addBBands()
addMACD()
addRSI()
```
#get the returns
```{r}
returns = dailyReturn(EC$EC.Close)
head(returns)
```
#differences betwenn clolse and open price
```{r}
Diferrences = EC$EC.Close - EC$EC.Open
head(Diferrences)
```
#Do VaR method
```{r}
VaR(returns, p=0.95, method = "historical")
VaR(Diferrences, p=0.95, method = "historical")

```
#Testing
```{r}
chartSeries(returns)
chartSeries(Diferrences)
```

